In [114]:
import math
import pandas as pd
import numpy as np
from scipy.stats import norm

In [115]:
ace_list = {1:'depress', 2:'alcoabuse', 3:'drugabuse', 4:'prison',
            5:'patdivorce', 6:'phyabuse1', 7:'phyabuse2', 8:'verbalabuse',
            9:'sexabuse1', 10:'sexabuse2', 11:'sexabuse3', } #'0.1':'foodinsecure'

In [116]:
ace_list.values()

dict_values(['depress', 'alcoabuse', 'drugabuse', 'prison', 'patdivorce', 'phyabuse1', 'phyabuse2', 'verbalabuse', 'sexabuse1', 'sexabuse2', 'sexabuse3'])

In [117]:
bfdata = pd.read_csv('SCBRFSS.csv', low_memory=False)

In [118]:
bfdata.keys()

Index(['PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'HLTHPLN1', 'PERSDOC2', 'MEDCOST',
       'CHECKUP1', 'EXERANY2', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3',
       'ASTHNOW', 'CHCSCNCR', 'CHCOCNCR', 'CHCCOPD1', 'HAVARTH3', 'ADDEPEV2',
       'CHCKIDNY', 'DIABETE3', 'AGE', 'VETERAN3', 'MARITAL', 'CHILDREN',
       'EMPLOY1', 'CTYCODE1', 'RENTHOM1', 'SEX', 'PREGNANT', 'BLIND', 'DECIDE',
       'DIFFWALK', 'DIFFDRES', 'DIFFALON', 'STOPSMK2', '_STSTR', '_RACE_G1',
       '_BMI5CAT', '_EDUCAG', '_INCOMG', '_SMOKER3', 'DRNKANY5', '_RFBING5',
       '_rfdrhv5', 'new_wt', 'depress', 'alcoabuse', 'drugabuse', 'prison',
       'patdivorce', 'phyabuse1', 'phyabuse2', 'verbalabuse', 'sexabuse1',
       'sexabuse2', 'sexabuse3', 'DEAF', '_ECIGSTS', 'rrclass',
       'rr_class_other', 'rrcognt', 'rratwork', 'rrhcare', 'rrphysym',
       'rremtsym', 'foodinsecure', 'homeless', 'ace_dentist', 'safehome',
       'HSgrad_mom', 'HSgrad_dad', 'singleparent', 'basicneeds'],
      dtype='object')

In [119]:
bfdata['_INCOMG'].unique()

array([5, 4, 9, 2, 3, 1])

In [120]:
bfdata['_RACE_G1'].unique()

array([ 3.,  2.,  5.,  1., nan,  4.])

In [121]:
for ace in ace_list.values():
    print(ace, bfdata[ace].unique())

depress [nan  2.  1.  9.  7.]
alcoabuse [nan  2.  1.  7.  9.]
drugabuse [nan  2.  1.  7.  9.]
prison [nan  2.  1.  7.  9.]
patdivorce [nan  2.  1.  8.  7.  9.]
phyabuse1 [nan  1.  3.  9.  7.  2.]
phyabuse2 [nan  1.  3.  2.  9.  7.]
verbalabuse [nan  3.  1.  2.  7.  9.]
sexabuse1 [nan  1.  2.  7.  3.  9.]
sexabuse2 [nan  1.  2.  7.  3.  9.]
sexabuse3 [nan  1.  3.  2.  7.  9.]


In [122]:
bfdata[bfdata['patdivorce'] == 8]

PHYSHLTH  MENTHLTH  POORHLTH  HLTHPLN1  PERSDOC2  MEDCOST  CHECKUP1  \
170           5        88      88.0         1         3        2         1   
311          88        15       6.0         2         1        1         1   
333          30        77      77.0         1         1        2         1   
461           4        88      88.0         1         1        2         1   
495          23         7      21.0         1         1        1         1   
...         ...       ...       ...       ...       ...      ...       ...   
33680        88        88       NaN         1         1        2         2   
33695        88         5      88.0         1         1        2         3   
33714        88        88       NaN         1         1        2         1   
33757        88        88       NaN         1         1        2         1   
33811         5         6      30.0         2         1        1         3   

       EXERANY2  CVDINFR4  CVDCRHD4  ...  rrphysym  rremtsym  foodinsecure  \
170         1.0         2         2  ...       NaN       NaN           NaN   
311         1.0         2         2  ...       NaN       NaN           NaN   
333         2.0         2         1  ...       NaN       NaN           NaN   
461         1.0         2         2  ...       NaN       NaN           NaN   
495         2.0         2         2  ...       NaN       NaN           NaN   
...         ...       ...       ...  ...       ...       ...           ...   
33680       2.0         2         2  ...       2.0       2.0           2.0   
33695       1.0         2         2  ...       2.0       2.0           1.0   
33714       2.0         2         2  ...       2.0       2.0           1.0   
33757       1.0         2         2  ...       2.0       2.0           5.0   
33811       1.0         1         2  ...       2.0       2.0           1.0   

       homeless  ace_dentist  safehome  HSgrad_mom  HSgrad_dad  singleparent  \
170         NaN          NaN       NaN         NaN         NaN           NaN   
311         NaN          NaN       NaN         NaN         NaN           NaN   
333         NaN          NaN       NaN         NaN         NaN           NaN   
461         NaN          NaN       NaN         NaN         NaN           NaN   
495         NaN          NaN       NaN         NaN         NaN           NaN   
...         ...          ...       ...         ...         ...           ...   
33680       2.0          1.0       5.0         7.0         2.0           5.0   
33695       1.0          1.0       4.0         1.0         2.0           5.0   
33714       1.0          7.0       5.0         1.0         1.0           2.0   
33757       1.0          1.0       1.0         1.0         7.0           4.0   
33811       1.0          1.0       5.0         2.0         7.0           5.0   

       basicneeds  
170           NaN  
311           NaN  
333           NaN  
461           NaN  
495           NaN  
...           ...  
33680         4.0  
33695         5.0  
33714         5.0  
33757         5.0  
33811         5.0  

[560 rows x 73 columns]

In [123]:
bfdata['_INCOMG'].unique()

array([5, 4, 9, 2, 3, 1])

In [124]:
bfdata['_RACE_G1'].unique()

array([ 3.,  2.,  5.,  1., nan,  4.])

In [125]:
race_list = {1:'White', 2:'Black', 3:'Hispanic', 4:'Other', 5:'Multi'}

In [126]:
income_list = {1:'< 15000', 2:'15000 - 24999', 3:'25000 - 34999', 
               4:'35000 - 49999', 5:'50000 +', 9:'Don\'t Know'}

In [127]:
w_15 = bfdata[(bfdata[['_RACE_G1', '_INCOMG']] == [1,1]).all(axis=1)]

In [128]:
w_15 = w_15[w_15['depress'].isin([1,2])]

In [129]:
w_15

PHYSHLTH  MENTHLTH  POORHLTH  HLTHPLN1  PERSDOC2  MEDCOST  CHECKUP1  \
154          88        88       NaN         2         3        2         1   
163          30        30      88.0         1         1        2         1   
187          88         2      88.0         1         1        2         1   
220          30        30      88.0         1         1        2         1   
227           3        15      15.0         1         1        2         3   
...         ...       ...       ...       ...       ...      ...       ...   
33729         5        88       2.0         1         2        2         1   
33730        88        88       NaN         1         1        1         2   
33735        99        88      30.0         1         1        2         1   
33813        30        30      24.0         1         1        1         2   
33815        30        10      30.0         1         2        2         1   

       EXERANY2  CVDINFR4  CVDCRHD4  ...  rrphysym  rremtsym  foodinsecure  \
154         1.0         2         2  ...       NaN       NaN           NaN   
163         2.0         1         1  ...       NaN       NaN           NaN   
187         1.0         2         2  ...       NaN       NaN           NaN   
220         1.0         2         2  ...       NaN       NaN           NaN   
227         1.0         2         2  ...       NaN       NaN           NaN   
...         ...       ...       ...  ...       ...       ...           ...   
33729       1.0         2         2  ...       2.0       2.0           1.0   
33730       2.0         2         2  ...       2.0       2.0           1.0   
33735       1.0         2         2  ...       2.0       2.0           1.0   
33813       2.0         2         2  ...       2.0       1.0           3.0   
33815       2.0         2         2  ...       2.0       2.0           1.0   

       homeless  ace_dentist  safehome  HSgrad_mom  HSgrad_dad  singleparent  \
154         NaN          NaN       NaN         NaN         NaN           NaN   
163         NaN          NaN       NaN         NaN         NaN           NaN   
187         NaN          NaN       NaN         NaN         NaN           NaN   
220         NaN          NaN       NaN         NaN         NaN           NaN   
227         NaN          NaN       NaN         NaN         NaN           NaN   
...         ...          ...       ...         ...         ...           ...   
33729       1.0          1.0       5.0         1.0         1.0           1.0   
33730       1.0          8.0       5.0         1.0         1.0           1.0   
33735       1.0          3.0       5.0         1.0         2.0           1.0   
33813       3.0          2.0       4.0         1.0         1.0           4.0   
33815       1.0          3.0       5.0         2.0         2.0           1.0   

       basicneeds  
154           NaN  
163           NaN  
187           NaN  
220           NaN  
227           NaN  
...           ...  
33729         5.0  
33730         5.0  
33735         5.0  
33813         5.0  
33815         5.0  

[1384 rows x 73 columns]

In [130]:
prop = (w_15['depress'] == 1).sum()/len(w_15); prop

0.21170520231213874

In [131]:
(w_15['depress'] == 1).sum()

293

In [132]:
(w_15['depress'] == 2).sum()

1091

In [133]:
(w_15['depress'] == 7).sum()

0

In [134]:
(w_15['depress'] == 9).sum()

0

In [135]:
w_15['depress'].sem(ddof=0)

0.010981004013833038

In [136]:
se = math.sqrt(prop*(1-prop)/len(w_15)); se

0.010981004013833038

In [137]:
prop + norm.ppf(0.975) * se

0.23322757469334127

In [138]:
prop - norm.ppf(0.975) * se

0.19018282993093621

In [139]:
ace_list.values()

dict_values(['depress', 'alcoabuse', 'drugabuse', 'prison', 'patdivorce', 'phyabuse1', 'phyabuse2', 'verbalabuse', 'sexabuse1', 'sexabuse2', 'sexabuse3'])

In [140]:
def get_dist(gpdata, ace_type):
    groupa = list(ace_list.values())[0:5]
    groupb = list(ace_list.values())[5:]
    
    if ace_type in groupa:
        dlen = (gpdata[ace].isin([1,2])).sum()
        prop = (gpdata[ace] == 1).sum()/dlen
        
    else:
        dlen = (gpdata[ace].isin([1,2,3])).sum()
        prop = (gpdata[ace].isin([2,3])).sum()/dlen
    se = math.sqrt(prop*(1-prop)/dlen)
    return [prop, se, prop - norm.ppf(0.975) * se, prop + norm.ppf(0.975)* se]

In [141]:
res_index = [[], [], []]
res_dist = []
for ace in ace_list.values():
    for r in race_list.keys():
        for i in income_list.keys():
            gpdata = bfdata[(bfdata[['_RACE_G1', '_INCOMG']] == [r,i]).all(axis=1)]
            # print([r,i], len(gpdata), get_dist(gpdata, ace))
            res_dist.append(get_dist(gpdata, ace))
            res_index[0].append(ace)
            res_index[1].append(race_list[r])
            res_index[2].append(income_list[i])
# print(res_index)

In [142]:
df = pd.DataFrame(res_dist, columns=['Proportion', 'Standard Error', 
                                     'L 95% CI', 'U 95% CI'], index=res_index)

In [143]:
df

Proportion  Standard Error  L 95% CI  U 95% CI
depress   White < 15000          0.211705        0.010981  0.190183  0.233228
                15000 - 24999    0.163790        0.007248  0.149584  0.177996
                25000 - 34999    0.146769        0.008281  0.130538  0.163000
                35000 - 49999    0.153333        0.006934  0.139743  0.166924
                50000 +          0.141829        0.003853  0.134278  0.149380
...                                   ...             ...       ...       ...
sexabuse3 Multi 15000 - 24999    0.166667        0.036901  0.094343  0.238991
                25000 - 34999    0.060000        0.033586 -0.005827  0.125827
                35000 - 49999    0.059524        0.025815  0.008926  0.110121
                50000 +          0.054264        0.019945  0.015171  0.093356
                Don't Know       0.120000        0.037523  0.046456  0.193544

[330 rows x 4 columns]

In [144]:
df.loc['depress']

Proportion  Standard Error  L 95% CI  U 95% CI
White    < 15000          0.211705        0.010981  0.190183  0.233228
         15000 - 24999    0.163790        0.007248  0.149584  0.177996
         25000 - 34999    0.146769        0.008281  0.130538  0.163000
         35000 - 49999    0.153333        0.006934  0.139743  0.166924
         50000 +          0.141829        0.003853  0.134278  0.149380
         Don't Know       0.108592        0.005560  0.097694  0.119489
Black    < 15000          0.083449        0.007293  0.069155  0.097743
         15000 - 24999    0.079953        0.006576  0.067064  0.092842
         25000 - 34999    0.073341        0.008895  0.055908  0.090775
         35000 - 49999    0.067715        0.008737  0.050590  0.084839
         50000 +          0.084615        0.007719  0.069487  0.099744
         Don't Know       0.060660        0.007130  0.046687  0.074634
Hispanic < 15000          0.174603        0.047829  0.080861  0.268345
         15000 - 24999    0.076336        0.023200  0.030865  0.121807
         25000 - 34999    0.138889        0.040757  0.059008  0.218770
         35000 - 49999    0.090909        0.035386  0.021553  0.160265
         50000 +          0.190141        0.032930  0.125598  0.254683
         Don't Know       0.216216        0.047855  0.122422  0.310010
Other    < 15000          0.250000        0.052511  0.147081  0.352919
         15000 - 24999    0.178571        0.041788  0.096669  0.260474
         25000 - 34999    0.203390        0.052404  0.100681  0.306099
         35000 - 49999    0.183673        0.055317  0.075255  0.292092
         50000 +          0.095890        0.024368  0.048130  0.143651
         Don't Know       0.128205        0.037854  0.054013  0.202398
Multi    < 15000          0.263889        0.051942  0.162085  0.365693
         15000 - 24999    0.285714        0.044087  0.199306  0.372123
         25000 - 34999    0.352941        0.066917  0.221786  0.484097
         35000 - 49999    0.178571        0.041788  0.096669  0.260474
         50000 +          0.269231        0.038903  0.192983  0.345479
         Don't Know       0.226667        0.048344  0.131913  0.321420

In [145]:
df.keys()

Index(['Proportion', 'Standard Error', 'L 95% CI', 'U 95% CI'], dtype='object')

In [146]:
df.index

MultiIndex([(  'depress', 'White',       '< 15000'),
            (  'depress', 'White', '15000 - 24999'),
            (  'depress', 'White', '25000 - 34999'),
            (  'depress', 'White', '35000 - 49999'),
            (  'depress', 'White',       '50000 +'),
            (  'depress', 'White',    'Don't Know'),
            (  'depress', 'Black',       '< 15000'),
            (  'depress', 'Black', '15000 - 24999'),
            (  'depress', 'Black', '25000 - 34999'),
            (  'depress', 'Black', '35000 - 49999'),
            ...
            ('sexabuse3', 'Other', '25000 - 34999'),
            ('sexabuse3', 'Other', '35000 - 49999'),
            ('sexabuse3', 'Other',       '50000 +'),
            ('sexabuse3', 'Other',    'Don't Know'),
            ('sexabuse3', 'Multi',       '< 15000'),
            ('sexabuse3', 'Multi', '15000 - 24999'),
            ('sexabuse3', 'Multi', '25000 - 34999'),
            ('sexabuse3', 'Multi', '35000 - 49999'),
            ('sexabuse3', 'Mul