In [120]:
import pandas as pd
import numpy as np

In [121]:
data_prex = '2010_ver1_45079_synth_'
pdata_file = data_prex + 'people.txt'
hdata_file = data_prex + 'households.txt'

In [122]:
pdata = pd.read_csv(pdata_file, dtype = {'sp_id': object, 'sp_hh_id': object})
hdata = pd.read_csv(hdata_file, dtype = {'sp_id': object})

In [123]:
pdata.columns

Index(['sp_id', 'sp_hh_id', 'serialno', 'stcotrbg', 'age', 'sex', 'race',
       'sporder', 'relate', 'sp_school_id', 'sp_work_id'],
      dtype='object')

In [124]:
hdata.columns

Index(['sp_id', 'serialno', 'stcotrbg', 'hh_race', 'hh_income', 'hh_size',
       'hh_age', 'latitude', 'longitude'],
      dtype='object')

In [125]:
pdata

sp_id  sp_hh_id       serialno      stcotrbg  age  sex  race  \
0       164099532  48930706  2007000946631  450790101032   49    2     2   
1       164099533  48930706  2007000946631  450790101032   57    1     2   
2       164099534  48954569  2007000946631  450790104073   49    2     2   
3       164099535  48954569  2007000946631  450790104073   57    1     2   
4       164099538  48964134  2007000946631  450790107022   49    2     2   
...           ...       ...            ...           ...  ...  ...   ...   
352053  164066165  48841329  2007000945819  450790112012   50    1     1   
352054  164066169  48822193  2007000945819  450790026021   50    1     1   
352055  164066170  48815049  2007000945819  450790021001   50    1     1   
352056  164066171  48811092  2007000945819  450790011003   50    1     1   
352057  164066175  48812365  2007000945819  450790012001   50    1     1   

        sporder  relate  sp_school_id   sp_work_id  
0             1       0           NaN  512875439.0  
1             2       1           NaN  512800369.0  
2             1       0           NaN  512809720.0  
3             2       1           NaN  512817555.0  
4             1       0           NaN  512795402.0  
...         ...     ...           ...          ...  
352053        1       0           NaN  512796496.0  
352054        1       0           NaN  512794808.0  
352055        1       0           NaN  512811317.0  
352056        1       0           NaN  512881787.0  
352057        1       0           NaN  512800240.0  

[352058 rows x 11 columns]

In [126]:
hdata

sp_id       serialno      stcotrbg  hh_race  hh_income  hh_size  \
0       48803425  2009000297596  450790001001        1      25000        1   
1       48803426  2008000705129  450790001001        2       7600        1   
2       48803427  2011000228204  450790001001        2      14800        4   
3       48803428  2008000644175  450790001001        2      14200        2   
4       48803429  2011000422107  450790001001        2      84001        1   
...          ...            ...           ...      ...        ...      ...   
145178  49027221  2010001250441  450790120004        2      18000        4   
145179  49027222  2007001371274  450790120004        1      11700        1   
145180  49027223  2011000238473  450790120004        2      26000        2   
145181  49027224  2009000547269  450790120004        1      27800        1   
145182  49027225  2011001174245  450790120004        1      53000        1   

        hh_age   latitude  longitude  
0           27  34.055366 -81.011849  
1           55  34.055765 -81.012221  
2           60  34.055749 -81.011905  
3           37  34.055623 -81.011567  
4           71  34.055375 -81.012428  
...        ...        ...        ...  
145178      48  33.805279 -80.634912  
145179      68  33.887353 -80.727873  
145180      40  33.887845 -80.728196  
145181      56  33.839339 -80.726391  
145182      76  33.839214 -80.726525  

[145183 rows x 9 columns]

In [127]:
pdata = pdata.drop(columns=['serialno', 'stcotrbg', 'sp_school_id', 'sp_work_id'])

In [128]:
pdata

sp_id  sp_hh_id  age  sex  race  sporder  relate
0       164099532  48930706   49    2     2        1       0
1       164099533  48930706   57    1     2        2       1
2       164099534  48954569   49    2     2        1       0
3       164099535  48954569   57    1     2        2       1
4       164099538  48964134   49    2     2        1       0
...           ...       ...  ...  ...   ...      ...     ...
352053  164066165  48841329   50    1     1        1       0
352054  164066169  48822193   50    1     1        1       0
352055  164066170  48815049   50    1     1        1       0
352056  164066171  48811092   50    1     1        1       0
352057  164066175  48812365   50    1     1        1       0

[352058 rows x 7 columns]

In [129]:
hdata = hdata[['sp_id', 'hh_income']]

In [130]:
hdata

sp_id  hh_income
0       48803425      25000
1       48803426       7600
2       48803427      14800
3       48803428      14200
4       48803429      84001
...          ...        ...
145178  49027221      18000
145179  49027222      11700
145180  49027223      26000
145181  49027224      27800
145182  49027225      53000

[145183 rows x 2 columns]

In [131]:
phdata = pd.merge(pdata, hdata, left_on=['sp_hh_id'], right_on = ['sp_id'])

In [132]:
phdata

sp_id_x  sp_hh_id  age  sex  race  sporder  relate   sp_id_y  \
0       164099532  48930706   49    2     2        1       0  48930706   
1       164099533  48930706   57    1     2        2       1  48930706   
2       164099534  48954569   49    2     2        1       0  48954569   
3       164099535  48954569   57    1     2        2       1  48954569   
4       164099538  48964134   49    2     2        1       0  48964134   
...           ...       ...  ...  ...   ...      ...     ...       ...   
352053  164066165  48841329   50    1     1        1       0  48841329   
352054  164066169  48822193   50    1     1        1       0  48822193   
352055  164066170  48815049   50    1     1        1       0  48815049   
352056  164066171  48811092   50    1     1        1       0  48811092   
352057  164066175  48812365   50    1     1        1       0  48812365   

        hh_income  
0          115000  
1          115000  
2          115000  
3          115000  
4          115000  
...           ...  
352053      90000  
352054      90000  
352055      90000  
352056      90000  
352057      90000  

[352058 rows x 9 columns]

In [133]:
cdn_data = phdata[phdata['age'] < 18]

In [134]:
cdn_data

sp_id_x  sp_hh_id  age  sex  race  sporder  relate   sp_id_y  \
102     164426008  48996117    4    1     2        3       2  48996117   
103     164426009  48996117    0    1     2        4       2  48996117   
106     164426012  49005231    4    1     2        3       2  49005231   
107     164426013  49005231    0    1     2        4       2  49005231   
110     164426016  48930748    4    1     2        3       2  48930748   
...           ...       ...  ...  ...   ...      ...     ...       ...   
352036  163958884  48979669    3    1     1        2       2  48979669   
352038  163971928  48840456    5    1     2        2       2  48840456   
352041  163971943  48804862    5    1     2        2       2  48804862   
352044  163971964  48836724    5    1     2        2       2  48836724   
352047  163971973  48844545    5    1     2        2       2  48844545   

        hh_income  
102         97000  
103         97000  
106         97000  
107         97000  
110         97000  
...           ...  
352036      42000  
352038      46420  
352041      46420  
352044      46420  
352047      46420  

[90314 rows x 9 columns]

In [135]:
pdata[pdata['age'] < 18]

sp_id  sp_hh_id  age  sex  race  sporder  relate
87      164426020  48969032    4    1     2        3       2
88      164426021  48969032    0    1     2        4       2
90      164426025  49009131    0    1     2        4       2
91      164426028  49000829    4    1     2        3       2
92      164426032  49022492    4    1     2        3       2
...           ...       ...  ...  ...   ...      ...     ...
352021  163971967  48824939    5    1     2        2       2
352024  163971973  48844545    5    1     2        2       2
352031  163971985  48832927    5    1     2        2       2
352033  163971988  48836562    5    1     2        2       2
352036  163971994  48834465    5    1     2        2       2

[90314 rows x 7 columns]

In [136]:
phdata['age']

0         49
1         57
2         49
3         57
4         49
          ..
352053    50
352054    50
352055    50
352056    50
352057    50
Name: age, Length: 352058, dtype: int64

In [137]:
phdata['sp_id_x']

0         164099532
1         164099533
2         164099534
3         164099535
4         164099538
            ...    
352053    164066165
352054    164066169
352055    164066170
352056    164066171
352057    164066175
Name: sp_id_x, Length: 352058, dtype: object

In [138]:
cdn_data['age']

102       4
103       0
106       4
107       0
110       4
         ..
352036    3
352038    5
352041    5
352044    5
352047    5
Name: age, Length: 90314, dtype: int64

In [139]:
max(cdn_data['age'])

17

In [140]:
cdn_data

sp_id_x  sp_hh_id  age  sex  race  sporder  relate   sp_id_y  \
102     164426008  48996117    4    1     2        3       2  48996117   
103     164426009  48996117    0    1     2        4       2  48996117   
106     164426012  49005231    4    1     2        3       2  49005231   
107     164426013  49005231    0    1     2        4       2  49005231   
110     164426016  48930748    4    1     2        3       2  48930748   
...           ...       ...  ...  ...   ...      ...     ...       ...   
352036  163958884  48979669    3    1     1        2       2  48979669   
352038  163971928  48840456    5    1     2        2       2  48840456   
352041  163971943  48804862    5    1     2        2       2  48804862   
352044  163971964  48836724    5    1     2        2       2  48836724   
352047  163971973  48844545    5    1     2        2       2  48844545   

        hh_income  
102         97000  
103         97000  
106         97000  
107         97000  
110         97000  
...           ...  
352036      42000  
352038      46420  
352041      46420  
352044      46420  
352047      46420  

[90314 rows x 9 columns]

In [141]:
max(cdn_data['relate'])

12

In [142]:
cdn_data['relate'].unique()

array([ 2,  5,  7,  3, 12, 11, 10,  8])

In [143]:
cdn_data['race'].unique()

array([2, 1, 8, 6, 9, 5, 7, 3])

In [144]:
cdn_data['sex'].unique()

array([1, 2])

In [145]:
cdn_data['age'].unique()

array([ 4,  0, 12, 10, 15,  5,  7,  9,  2, 16,  3,  6, 17, 11,  8, 14, 13,
        1])

In [146]:
cdn_data.loc[0:1]

Empty DataFrame
Columns: [sp_id_x, sp_hh_id, age, sex, race, sporder, relate, sp_id_y, hh_income]
Index: []

In [147]:
cdn_data

sp_id_x  sp_hh_id  age  sex  race  sporder  relate   sp_id_y  \
102     164426008  48996117    4    1     2        3       2  48996117   
103     164426009  48996117    0    1     2        4       2  48996117   
106     164426012  49005231    4    1     2        3       2  49005231   
107     164426013  49005231    0    1     2        4       2  49005231   
110     164426016  48930748    4    1     2        3       2  48930748   
...           ...       ...  ...  ...   ...      ...     ...       ...   
352036  163958884  48979669    3    1     1        2       2  48979669   
352038  163971928  48840456    5    1     2        2       2  48840456   
352041  163971943  48804862    5    1     2        2       2  48804862   
352044  163971964  48836724    5    1     2        2       2  48836724   
352047  163971973  48844545    5    1     2        2       2  48844545   

        hh_income  
102         97000  
103         97000  
106         97000  
107         97000  
110         97000  
...           ...  
352036      42000  
352038      46420  
352041      46420  
352044      46420  
352047      46420  

[90314 rows x 9 columns]

In [148]:
for i, row in cdn_data.iterrows():
    type(row)

In [149]:
cdn_data.keys()

Index(['sp_id_x', 'sp_hh_id', 'age', 'sex', 'race', 'sporder', 'relate',
       'sp_id_y', 'hh_income'],
      dtype='object')

In [150]:
len(cdn_data)

90314

In [151]:
from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.datacollection import DataCollector

In [152]:
income_cat = [0, 15000, 24999, 34999, 49999]

race_cat = [1,2,3,4,5]
ace_dist = {1:[0.2117052, 0.1637898, 0.1467698, 0.1533333, 0.1418293, 0.1085915], 
            2:[0.0834492, 0.0799530, 0.0733411, 0.0677146, 0.0846154, 0.0606601], 
            3:[0.1746032, 0.0763359, 0.1388889, 0.0909091, 0.1901408, 0.2162162], 
            4:[0.2500000, 0.1785714, 0.2033898, 0.1836735, 0.0958904, 0.1282051], 
            5:[0.2638889, 0.2857143, 0.3529412, 0.1785714, 0.2692308, 0.2266667]}

def cat_income(hh_income):
    if pd.isnull(hh_income):
        return 5
    if hh_income >= income_cat[0] and hh_income < income_cat[1]:
        return 0
    if hh_income >= income_cat[1] and hh_income < income_cat[2]:
        return 1
    if hh_income >= income_cat[2] and hh_income < income_cat[3]:
        return 2
    if hh_income >= income_cat[3] and hh_income < income_cat[4]:
        return 3
    if hh_income >= income_cat[4]:
        return 4

def cat_race(chd_race):
    if pd.isnull(chd_race):
        return 4
    if chd_race == 1:
        return 1
    if chd_race == 2:
        return 2
    if chd_race == 9:
        return 5
    return 4
    

In [153]:
def output_model(model):
    # agents = [a.output() 
    #          for i, sch_list in model.sch_group.items()
    #          for scheduler in sch_list 
    #          for a in scheduler.agents ]
    agents = [a.output() for a in model.schedule.agents]
    return pd.DataFrame(agents, columns=['id', 'age', 'race', 'income', 'ace'])
    # return agents

In [154]:
class Children(Agent):
            
    def __init__(self, chd_info, model, pos = None):
        unique_id = chd_info['sp_id_x']
        super().__init__(unique_id, model)
        self.pos = pos
        self.ace = 0
        self.age = chd_info['age']
        self.sex = chd_info['sex']
        self.income = chd_info['hh_income']
        self.race = chd_info['race']
        
    def step(self):
        p_aces = self.model.random.random()
        dist_cat = ace_dist[cat_race(self.race)][cat_income(self.income)]
        if p_aces < dist_cat:
            self.ace = 1
        else:
            self.ace = 0
            
    def get_cat(self):
        return cat_race(self.race), cat_income(self.income)
    
    def output(self):
        return [self.unique_id, self.age, self.race, self.income, self.ace]

In [155]:
class AceModel(Model):
    def __init__(self, chd_data):
        self.num_agents = len(chd_data)
        self.schedule = RandomActivation(self)
        self.sch_group = {x: [RandomActivation(self) 
                              for i in range(len(income_cat) + 1)] 
                          for x in race_cat}
        
        for i,chd_info in chd_data.iterrows():
            a = Children(chd_info, self)
            cat_r, cat_i = a.get_cat()
            self.schedule.add(a)
            self.sch_group[cat_r][cat_i].add(a)
            
        self.datacollector = DataCollector(
            model_reporters = {'Output': output_model}            
        )
        
    def step(self):        
        for i, sch_list in self.sch_group.items():
            for scheduler in sch_list:
                self.reset_randomizer()
                scheduler.step()
        self.datacollector.collect(self)
        # self.schedule.step()

In [156]:
cdn_data['race'].unique()

array([2, 1, 8, 6, 9, 5, 7, 3])

In [157]:
len(cdn_data)

90314

In [158]:
acemodel = AceModel(cdn_data)

In [159]:
acemodel.step()

In [160]:
res =acemodel.datacollector.model_vars

In [161]:
res = res['Output']

In [162]:
res[-1]

id  age  race  income  ace
0      164426008    4     2   97000    0
1      164426009    0     2   97000    0
2      164426012    4     2   97000    0
3      164426013    0     2   97000    0
4      164426016    4     2   97000    0
...          ...  ...   ...     ...  ...
90309  163958884    3     1   42000    0
90310  163971928    5     2   46420    0
90311  163971943    5     2   46420    0
90312  163971964    5     2   46420    0
90313  163971973    5     2   46420    0

[90314 rows x 5 columns]

In [163]:
len(res)

1

In [164]:
test = res[-1]
test['race'].map(cat_race)

0        2
1        2
2        2
3        2
4        2
        ..
90309    1
90310    2
90311    2
90312    2
90313    2
Name: race, Length: 90314, dtype: int64

In [165]:
test

id  age  race  income  ace
0      164426008    4     2   97000    0
1      164426009    0     2   97000    0
2      164426012    4     2   97000    0
3      164426013    0     2   97000    0
4      164426016    4     2   97000    0
...          ...  ...   ...     ...  ...
90309  163958884    3     1   42000    0
90310  163971928    5     2   46420    0
90311  163971943    5     2   46420    0
90312  163971964    5     2   46420    0
90313  163971973    5     2   46420    0

[90314 rows x 5 columns]

In [166]:
test['race'].map(cat_race).unique()

array([2, 1, 4, 5])

In [167]:
test['race'].unique()

array([2, 1, 8, 6, 9, 5, 7, 3])

In [168]:
test['race'] = test['race'].map(cat_race)

In [169]:
test

id  age  race  income  ace
0      164426008    4     2   97000    0
1      164426009    0     2   97000    0
2      164426012    4     2   97000    0
3      164426013    0     2   97000    0
4      164426016    4     2   97000    0
...          ...  ...   ...     ...  ...
90309  163958884    3     1   42000    0
90310  163971928    5     2   46420    0
90311  163971943    5     2   46420    0
90312  163971964    5     2   46420    0
90313  163971973    5     2   46420    0

[90314 rows x 5 columns]

In [170]:
test['race'].unique()

array([2, 1, 4, 5])

In [171]:
test['income'].map(cat_income).unique()

array([4, 0, 3, 2, 1])

In [172]:
test['income'] = test['income'].map(cat_income)

In [173]:
test

id  age  race  income  ace
0      164426008    4     2       4    0
1      164426009    0     2       4    0
2      164426012    4     2       4    0
3      164426013    0     2       4    0
4      164426016    4     2       4    0
...          ...  ...   ...     ...  ...
90309  163958884    3     1       3    0
90310  163971928    5     2       3    0
90311  163971943    5     2       3    0
90312  163971964    5     2       3    0
90313  163971973    5     2       3    0

[90314 rows x 5 columns]

In [207]:
prop_list = []

In [208]:
print('race\tincome\tprop_simu\tprop_brfss\tdiff')

for r in [1,2,4,5]:
    for i in [0,1,2,3,4]:
        tmp = test[(test[['race', 'income']] == [r,i]).all(axis = 'columns')]
        print('{}\t{}\t{:.7f}\t{:.7f}\t{: .7f}'.format(r, i, sum(tmp['ace'])/len(tmp), ace_dist[r][i], sum(tmp['ace'])/len(tmp) - ace_dist[r][i]))

race	income	prop_simu	prop_brfss	diff
1	0	0.2068729	0.2117052	-0.0048323
1	1	0.1756329	0.1637898	 0.0118431
1	2	0.1418812	0.1467698	-0.0048886
1	3	0.1412722	0.1533333	-0.0120611
1	4	0.1432156	0.1418293	 0.0013863
2	0	0.0774037	0.0834492	-0.0060455
2	1	0.0801829	0.0799530	 0.0002299
2	2	0.0769231	0.0733411	 0.0035820
2	3	0.0707293	0.0677146	 0.0030147
2	4	0.0827522	0.0846154	-0.0018632
4	0	0.2673267	0.2500000	 0.0173267
4	1	0.1606805	0.1785714	-0.0178909
4	2	0.1768293	0.2033898	-0.0265605
4	3	0.1780303	0.1836735	-0.0056432
4	4	0.0972316	0.0958904	 0.0013412
5	0	0.2318841	0.2638889	-0.0320048
5	1	0.2473573	0.2857143	-0.0383570
5	2	0.3757829	0.3529412	 0.0228417
5	3	0.1723077	0.1785714	-0.0062637
5	4	0.2808731	0.2692308	 0.0116423


In [214]:
for t in range(100):
    acemodel.step()
    test = (acemodel.datacollector.model_vars)['Output'][-1]
    test['race'] = test['race'].map(cat_race)
    test['income'] = test['income'].map(cat_income)
    prop = []
    for r in [1,2,4,5]:
        for i in [0,1,2,3,4]:
            tmp = test[(test[['race', 'income']] == [r,i]).all(axis = 'columns')]
            prop.append(sum(tmp['ace'])/len(tmp))            
    prop_list.append(prop)

In [215]:
prop_pd = pd.DataFrame(prop_list)

In [216]:
tmp = []
for r in [1,2,4,5]:
    for i in [0,1,2,3,4]:
        tmp.append(ace_dist[r][i])

In [217]:
for dif in (prop_pd.apply(lambda x: sum(x)/len(x)) - pd.Series(tmp)):
    print('{: .7f}'.format(dif))

-0.0002791
-0.0004828
 0.0006133
 0.0003187
 0.0001260
-0.0002455
-0.0007997
 0.0002584
 0.0002633
-0.0002151
-0.0029703
-0.0004996
-0.0005036
 0.0024818
-0.0011436
 0.0022947
 0.0009665
 0.0006079
 0.0001824
 0.0012344


In [218]:
len(prop_pd)

200

In [219]:
prop_pd.sem(axis = 0)

0     0.000760
1     0.000732
2     0.000603
3     0.000522
4     0.000138
5     0.000197
6     0.000249
7     0.000217
8     0.000203
9     0.000143
10    0.002989
11    0.001213
12    0.001191
13    0.001693
14    0.000542
15    0.002295
16    0.001424
17    0.001510
18    0.001488
19    0.000774
dtype: float64